# Generated by Django 5.1.6 on 2025-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='application',
            field=models.TextField(blank=True, null=True, verbose_name='Сфера применения'),
        ),
        migrations.AddField(
            model_name='material',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='Способ применения'),
        ),
    ]
