# Generated by Django 5.1.6 on 2025-03-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_material_application_material_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='advantages',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые преимущества'),
        ),
    ]
